language: csharp

services:
  - docker

solution: TeteCore.sln
sudo: required
dist: xenial
mono: none
dotnet: 3.1
script:
  - dotnet restore
  - dotnet test
  - bash travis-docker-build.sh

deploy:
  - provider: script
    script: bash travis-deploy-dev.sh
    on:
      branch: develop
  - provider: script
    script: bash travis-deploy-prod.sh
    on:
      branch: production
