language: csharp

services:
  - docker

solution: TeteCore.sln
sudo: required
dist: xenial
mono: none
dotnet: 3.1
script:
  - dotnet restore
  - dotnet test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: develop
