---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tete-api
  namespace: tete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tete-api
  template:
    metadata:
      labels:
        app: tete-api
    spec:
      containers:
      - name: tete-api
        image: puremunky/tete-api:latest
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tete-web
  namespace: tete
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tete-web
  template:
    metadata:
      labels:
        app: tete-web
    spec:
      containers:
      - name: tete-web
        image: puremunky/tete-web:latest
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tete-db
  namespace: tete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tete-db
  template:
    metadata:
      labels:
        app: tete-db
    spec:
      containers:
      - name: tete-db
        image: puremunky/tete-db:latest
        ports:
        - containerPort: 80